
spring:
  datasource:
    username: root
    password: Af147258
    url: jdbc:mysql:///webdb3
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: auto #自增